// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package queries

import (
	"context"
)

const createChannel = `-- name: CreateChannel :one
INSERT INTO channels (name)
VALUES ($1)
RETURNING id, name
`

func (q *Queries) CreateChannel(ctx context.Context, name string) (Channel, error) {
	row := q.db.QueryRow(ctx, createChannel, name)
	var i Channel
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listChannels = `-- name: ListChannels :many
SELECT id, name
FROM channels
ORDER BY name ASC
`

func (q *Queries) ListChannels(ctx context.Context) ([]Channel, error) {
	rows, err := q.db.Query(ctx, listChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
