services:
  app:
    build:
      context: ./backend
    environment:
      DB_URL: "postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?sslmode=disable"
      GOCACHE: /tmp/.cache
    volumes:
      - ./backend/:/app
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
    volumes:
      - type: bind
        source: ./frontend
        target: /app
    environment:
      - VITE_API_URL=http://localhost:8000/api

  db:
    image: postgres:18.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
