services:
  db:
    healthcheck:
      interval: 1s
      timeout: 1s
      retries: 1

  app:
    build:
      target: test
    command: tail -f /dev/null

  frontend:
    build:
      target: test
    volumes:
      - /app/node_modules
