// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Channel struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Message struct {
	ID        int64              `json:"id"`
	ChannelID int64              `json:"channel_id"`
	Message   string             `json:"message"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
