// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package queries

import (
	"context"
)

const channelExists = `-- name: ChannelExists :one
SELECT EXISTS (
	SELECT 1 FROM channels WHERE id=$1
)
`

func (q *Queries) ChannelExists(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, channelExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createChannel = `-- name: CreateChannel :one
INSERT INTO channels (name)
VALUES ($1)
RETURNING id, name
`

func (q *Queries) CreateChannel(ctx context.Context, name string) (Channel, error) {
	row := q.db.QueryRow(ctx, createChannel, name)
	var i Channel
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages
(channel_id, message)
VALUES ($1, $2)
RETURNING id, channel_id, message
`

type CreateMessageParams struct {
	ChannelID int64  `json:"channel_id"`
	Message   string `json:"message"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.ChannelID, arg.Message)
	var i Message
	err := row.Scan(&i.ID, &i.ChannelID, &i.Message)
	return i, err
}

const listChannels = `-- name: ListChannels :many
SELECT id, name
FROM channels
ORDER BY name ASC
`

func (q *Queries) ListChannels(ctx context.Context) ([]Channel, error) {
	rows, err := q.db.Query(ctx, listChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const messagesInChannel = `-- name: MessagesInChannel :many
SELECT id, channel_id, message
FROM messages
WHERE channel_id = $1
`

func (q *Queries) MessagesInChannel(ctx context.Context, channelID int64) ([]Message, error) {
	rows, err := q.db.Query(ctx, messagesInChannel, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(&i.ID, &i.ChannelID, &i.Message); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
